config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    
    collection do
      #瀏覽所有餐廳的最新動態
      get :feeds

      #top10 人氣餐廳
      get :ranking
    end

    #瀏覽個別餐廳的dashboard
    member do
      get :dashboard
    end

    #favorite/unfavorite
    member do
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end


  end
  
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy] 

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant, counter_cache: true
  # counter_cache 可以自動回傳 size 方法結果，計算關聯物件的數量
  # 必須在關聯 Model 上加一個欄位，慣例命名為 {table_name}_count
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  #排序
  default_scope { order(created_at: :desc)}

  belongs_to :category
  has_many :comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user  

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

  # 使用者評論餐廳=>多對多關聯
  has_many :comments, dependent: :destroy
  has_many :restaurants, through: :comments
  
  # 使用者收藏餐廳=>多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 使用者有很多追蹤紀錄(followships), 透過追蹤紀錄，一個User追蹤很多其他User(followings)
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # User 可以找到他的追蹤者
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private
    def authenticate_admin
      unless current_user.admin?
        flash[:alert] = "Not allow!"
        redirect_to root_path
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(following_id: params[:following_id])

    if @followship.save
      flash[:notice] = "Successfully followed"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @followship = current_user.followships.where(following_id: params[:id]).first
    @followship.destroy
    flash[:alert] = "Followship destroyed"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path) #導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end  

  #get ranking
  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, :except => :index

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants
    @followings = @user.followings
    @followers = @user.followers
    @favorited_restaurants = @user.favorited_restaurants
  end

  def edit
    redirect_to user_path(@user) unless @user == current_user
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">

  <h1>Edit Profile</h1>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>  
    
    <div class="form-group">
      <%= f.label :intro, "自我介紹" %>
      <%= f.text_area :intro, class: "form-control", rows: "2" %>
    </div>
  
    <div class="form-group">
      <%= f.label :avatar, "大頭照上傳" %>
      <%= image_tag @user.avatar, width: '150px' if @user.avatar? %>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-info btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-secondary btn-default" %>
    </div>
  <% end %>

</div>

app/views/users/index.html.erb
<div class="container">


  <!-- 導航列，各分頁連結 -->
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to '首頁', root_path %></li>
    <li role="presentation"><%= link_to '最新動態', feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %></li>
    <li role="presentation" class="active"><%= link_to '美食達人', users_path %></li>
  </ul>
  
  <h2>美食達人</h2>
  <hr>

  <div class="row equal">
    <% @users.each do |user| %>
      <div class="col-sm-4 col-xs-6 col-md-2 col-md-offset-1 text-center user_item">
        <%= image_tag user.avatar, class: "img-thumbnail", alt: "使用者未上傳圖片" %>
        <p><%= link_to user.name, user_path(user) %></p>
        <%= render partial: "shared/follow", locals: {user: user} %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <br>
    <div class="col-md-3 col-md-offset-1">
      <%= image_tag @user.avatar, class: "img-responsive" %>
    </div>
    
    <div class="col-md-7 ">
      <ul class="list-group">
        <li class="list-group-item">
          <span class="badge badge-primary badge-pill">Name</span><br>
          <h2><%= @user.name %></h2>
        </li>
        <li class="list-group-item">
          <span class="badge badge-primary badge-pill">Email</span><br>
          <%= @user.email %>    
        </li>
        <li class="list-group-item">
          <span class="badge badge-primary badge-pill">Intro</span><br>
          <%= @user.intro %>
        </li>
        <li class="list-group-item"><%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <!-- 自己去追蹤的人 -->
    <div class="col-md-3 col-md-offset-1 ">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= @followings.count %> followings
        </div>
        <div class="panel-body" style="max-height: 500px; overflow-y: scroll;">
          <% @followings.each do |following| %>
            <%= link_to(user_path(following)) do %>
              <div class="follow_list">
                <%= image_tag following.avatar, class: "img-circle img-thumbnail", alt: "使用者未上傳圖片"  %>
                <%= following.name %>
                <hr>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
    <!--已評論餐廳-->
    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-heading">已評論餐廳</div>
        <div class="panel-body" style="max-height: 500px; overflow-y: scroll;">
          <% @commented_restaurants = @commented_restaurants.uniq %>
          <% @commented_restaurants.each do |restaurant| %>
            <%= link_to(restaurant_path(restaurant)) do %>
              <div class="my-restaurant">
                <%= image_tag restaurant.image, class: "img img-thumbnail", alt: "尚未上傳圖片"  %>
                <p><%= restaurant.name %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>     
    </div>

    <!-- 追蹤自己的人 -->
    <div class="col-md-3 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= @followers.count %> followers
        </div>
        <div class="panel-body" style="max-height: 500px; overflow-y: scroll;">
          <% @followers.each do |follower| %>
            <%= link_to(user_path(follower)) do %>
              <div class="follow_list">
                <%= image_tag follower.avatar, class: "img-circle img-thumbnail", alt: "使用者未上傳圖片"  %>
                <%= follower.name %>
                <hr>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
    <!-- 收藏的餐廳 -->
    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= @favorited_restaurants.count %> 收藏的餐廳
        </div>
        <div class="panel-body" style="max-height: 500px; overflow-y: scroll;">
          <% @favorited_restaurants.each do |restaurant| %>
            <%= link_to(restaurant_path(restaurant)) do %>
              <div class="my-restaurant">
                <%= image_tag restaurant.image, class: "img img-thumbnail", alt: "尚未上傳圖片" %>
                <p><%= restaurant.name %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>