config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    
    collection do
      #瀏覽所有餐廳的最新動態
      get :feeds

      #top10 人氣餐廳
      get :ranking
    end

    #瀏覽個別餐廳的dashboard
    member do
      get :dashboard
    end

    #favorite/unfavorite
    member do
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end


  end
  
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy] 

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader

  #排序
  default_scope { order(created_at: :desc)}

  belongs_to :category
  has_many :comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user  

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path) #導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end  

  #get ranking
  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %> 筆評論</li>
  <li>這家餐廳的平均價位為 $xxx</li>
  <li>有 XX 人收藏這家餐廳</li>
</ul>

app/views/restaurants/feeds.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to '首頁', root_path %></li>
    <li role="presentation" class="active"><%= link_to '最新動態', feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to '美食達人', users_path %></li>
  </ul>
  
  <div class="row">
      <div class="col-md-offset-1"><h1>餐廳最新動態</h1></div>

      <div class="panel panel-default col-md-5 col-md-offset-1">
        <div class="panel-heading">
          <h3>最新餐廳</h3>
        </div>
        
        <div class="panel-body">
          <% @recent_restaurants.each do |restaurant| %>
          <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
          <p><%= restaurant.category.name %></p>
          <p><%= restaurant.description %></p>
          <% end %>
        </div>  
      </div>

      <div class="panel panel-default col-md-5 col-md-offset-1">
        <div class="panel-heading">
          <h3>最新評論</h3>
        </div>

        <div class="panel-body">
          <% @recent_comments.each do |comment| %>
          <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
          <p><%= comment.content %></p>
          <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
          <hr>
          <% end %>
        </div>
      </div>

  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><%= link_to '首頁', root_path %></li>
    <li role="presentation"><%= link_to '最新動態', feeds_restaurants_path %></li>
    <li role="presentation"><%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to '美食達人', users_path %></li>
  </ul>
  
  <div class="row">
    <ul class="nav nav-pills nav-pills-center ">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
    
    <br>

    <%= render partial: "shared/restaurant_list" %>  
  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
  
  <!--Nav Tabs -->
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to '首頁', root_path %></li>
    <li role="presentation"><%= link_to '最新動態', feeds_restaurants_path %></li>
    <li role="presentation" class="active"><%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %></li>
    <li role="presentation"><%= link_to '美食達人', users_path %></li>
  </ul>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="page-header">
        <h1>TOP 10 人氣餐廳<small>(收藏數最高)</small></h1>
      </div>

      <% @restaurants.each do |restaurant| %>
        
        <div class="ranking-item">
        
          <div class="col-md-3">
            <%= link_to restaurant_path(restaurant) do %>
              <%= image_tag restaurant.image, class: "img-responsive center-block" %>
            <% end %>
          </div>
          <div class="col-md-9">
            <h4><%= restaurant.name %></h4>
            <span>收藏數：<%= restaurant.favorites_count %></span>
            <p><%= truncate(restaurant.description, length: 200) %></p>
            <%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary" %>
            <%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %>
          </div>
          <div class="clearfix"></div>
        </div>
      <% end %>

    </div>
  </div>

  
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">

    <div class="page-header">
      <h1><%= @restaurant.name %></h1>
      <h5><%= @restaurant.category.name %></h5>
    </div>
      
      <div class="col-md-5">
        <%= image_tag @restaurant.image, class: "img-responsive" %>
        <br>
        <div class="well">
          <table>
            <tr>
              <th>Opening Hours: </th>
              <td><%= @restaurant.opening_hours %></td>
            </tr>
            <tr>
              <th>Tel: </th> 
              <td><%= @restaurant.tel %></td>
            </tr>
            <tr>
              <th>Address: </th>
              <td><%= @restaurant.address %></td>
            </tr>
          </table>
        </div>
      </div>
      
      <div class="col-md-8">
        <div class="well">
          <p><strong>Description: </strong></p>
          <p><%= @restaurant.description %></p>
        </div>
      </div>

  </div>

  <%= link_to "Dashboard", dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>

  <!-- favorite/unfavorite按鈕 -->
  <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
  <%= render partial: "shared/like", locals: {restaurant: @restaurant} %>

  <hr>
  <!-- 顯示與餐廳相關的評論 -->
  <% @restaurant.comments.each do |comment| %>
  <div>
    <h4><%= comment.user.name %></h4>
    <p><%= simple_format comment.content %></p>
    <p class="text-muted">
      <em><%= time_ago_in_words(comment.created_at) %> ago </em>
      <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
      <% end %>
    </p>
  </div>
  <hr>
  <% end %>

  <!-- 使用者輸入評論 -->
  <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>

  <%= link_to 'Back to index', restaurants_path %>
</div>